name: deepl
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=38.0.1
  - cython=0.29.32
  - fftw=3.3.9
  - flit-core=3.6.0
  - freetype=2.12.1
  - git=2.34.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libpng=1.6.37
  - libtiff=4.4.0
  - libuv=1.40.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openssl=1.1.1s
  - pillow=9.3.0
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.8
  - pytorch=1.13.1
  - pytorch-mutex=1.0
  - requests=2.28.1
  - scipy=1.9.3
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - tk=8.6.12
  - torchvision=0.14.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.13
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - contourpy==1.0.6
      - cycler==0.11.0
      - docopt==0.6.2
      - fonttools==4.38.0
      - kiwisolver==1.4.4
      - matplotlib==3.6.2
      - opencv-python==4.6.0.66
      - packaging==22.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
